export const ADD_ONE_PRODUCT = 'ADD_ONE_PRODUCT';
export const CLEAR_CART = 'CLEAR_CART';
export const DELETE_ONE_ITEM = 'DELETE_ONE_ITEM';
export const INCREASE_PRODUCT_COUNT = 'INCREASE_PRODUCT_COUNT';
export const DECREASE_PRODUCT_COUNT = 'DECREASE_PRODUCT_COUNT';

export const ADD_DEFAULT_VARIANTS = 'ADD_DEFAULT_VARIANTS';
export const DELETE_DEFAULT_VARIANTS = 'DELETE_DEFAULT_VARIANTS';
export const EDIT_DEFAULT_VARIANTS = 'EDIT_DEFAULT_VARIANTS';
